---
# tasks file for role-ohmyzsh
- name: Ensure all configured dotfiles are links.
  command: "sh -c $(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: existing_ohmyzsh_info
  failed_when: false
  check_mode: false
  changed_when: false